### ISSUE TITLE
Allow removing file name hashes

### ISSUE THREAD

**Issue by jakenuts** [ol-loginov/parcel-namer-rewrite#13]
The plugin works great when I 'parcel build' but when I use 'parcel watch' it adds/preserves hashes in all my icon names and I really just want the names to remain consistent. I was able to resolve this using the 'parcel-namer-custom' plugin which explicitly builds the names like "fonts/[name].[type]" and doesn't add hashes but I'd feel safer if I could use this plugin but remove hashes. I've tried setting developmentHashing and useParcelHash to false in my package.json parcel-namer-rewrite section but to no avail.

Thanks!

```
"parcel-namer-rewrite": {
  "developmentHashing": false,
  "useParcelHash ": false,
  "rules": {
	"(.*)\\.(css)": "css/$1.$2",
	"(.*)\\.(js)": "js/$1.$2",
	"(.*)\\.(eot|woff2?|svg|ttf)": "fonts/$1.$2",
	"(.*)\\.(png|gif|jpg)": "images/$1.$2"
  },
  "silent": false
},
```

**Comment by ol-loginov** [comment]
"useParcelHash" just uses hash provided by Parcel. Otherwise hash will be calculated from asset files (if applicable).

Regarding your issue: you may find version '2.0.0-rc.3' useful for that.

There is new option "hashing" was added, as well as configuration profiles.

Then you config will look like:

```json
"parcel-namer-rewrite": {
  "hashing": "never",
  "rules": {
	"(.*)\\.(css)": "css/$1.$2",
	"(.*)\\.(js)": "js/$1.$2",
	"(.*)\\.(eot|woff2?|svg|ttf)": "fonts/$1.$2",
	"(.*)\\.(png|gif|jpg)": "images/$1.$2"
  },
  "silent": false
},
```

You want to disable hashing in watch only, you may add some profile (for instance "hashless")
```json
"parcel-namer-rewrite": {
  "rules": {
	"(.*)\\.(css)": "css/$1.$2",
	"(.*)\\.(js)": "js/$1.$2",
	"(.*)\\.(eot|woff2?|svg|ttf)": "fonts/$1.$2",
	"(.*)\\.(png|gif|jpg)": "images/$1.$2"
  },
  "silent": false,
  "profiles": {
    "hashless": {
      "hashing": "never",
    }
  } 
},
```

and activate it with environment
```commandline
PARCEL-NAMER-REWRITE-PROFILE=hashless parcel watch ...
```
